config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"

  resources :articles

  get "/signup", to: "users#new"
  resources :users, except: [:new]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :category
    
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 3, maximum: 200}
    validates :user_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article
    validates :name, presence:true, 
    length: { minimum:3, maximum: 25}

    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    
    validates :username, presence:true, 
    uniqueness: {case_sensitive: false},
    length: { minimum:3, maximum: 25}

    VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

    validates :email, presence:true,
    uniqueness: {case_sensitive: false},
    format: { with: VALID_EMAIL_REGEX }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def show
    end

    def new
        @article = Article.new 
    end

    def create

        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article saved successfully!"
            redirect_to article_path(@article)
        else
            render 'new'
        end

        # render plain: params[:article].inspect
    end


    def edit
    end

    def update
        
        if @article.update(article_params)
            flash[:success] = "Article updated successfully!"
            redirect_to article_path(@article)
        else
            render 'edit'
        end

    end

    def destroy

        if @article.destroy
            flash[:success] = "Article deleted successfully"
        else
            flash[:notice] = "Something went wrong while deleting article"
        end

        redirect_to articles_path

    end

    private 

    def set_article
        @article = Article.find(params[:id]) 
    end

    def article_params
        params.require(:article).permit(:title, :description, :user_id)
    end

    def require_same_user
        if current_user != @article.user and !current_user.admin?
            flash[:danger] = "You must be the owner of the article to perform any action"
            redirect_to root_path
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :require_admin, except: [:index, :show]

    def index
        @categories = Category.all
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category create successfully"
            redirect_to categories_path
        else
            render 'new'
        end
    end

    def show

    end

    def edit
    end

    def update
        if @category.update(category_params)
            flash[:success] = "Category updated successfully"
            redirect_to categories_path
        else
            render 'edit'
        end
    end

    def destroy
        if @category.destroy
            flash[:success] = "Category deleted successfully"
            redirect_to categories_path
        end
    end

    private

    def set_category
        @category = Category.find(params[:id])
    end


    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !logged_in? || (logged_in? && !current_user.admin?)
            flash[:danger] = "Only admin users can perform such actions"
            redirect_to root_path
        end
    end

    


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    
    end

    def create
        user = User.find_by(email: params[:session][:email])

        if user && user.authenticate(params[:session][:password])
            flash[:success] = "Logged in sucessfully"
            session[:user_id] = user.id 
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Email or Password is wrong!"
            render 'new' 
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "Logged out successfully!"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_same_user, only: [:edit,:update]
    before_action :require_admin, only: [:destroy]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id

            flash[:success] = "Welcome to Rails blog #{@user.username}!"
            redirect_to articles_path
        else
            render 'new'
        end

    end

    def edit
    end

    def update

        if @user.update(user_params)
            flash[:success] = "Updated successfully!"

            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def destroy
        @user.destroy
        flash[:success] = "User and articles related to it have been deleted"
        redirect_to users_path
    end

    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end


    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user
            flash[:danger] = "You can only edit your own account"
            redirect_to root_path
        end
    end

    def require_admin
        if logged_in? && !current_user.admin?
            flash[:danger] = "Only admin user can delete"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>

    <div class="card-body bg-light mb-2">
        <h3><%= link_to article.title, article_path(article) %></h3>
        <p><%= truncate(article.description, length: 100) %></p>
        <small>Author : <%= (link_to article.user.username, user_path(article.user)) if article.user %> | </small>
        <small>Posted : <%= time_ago_in_words(article.created_at) %> ago | Last Updated : <%= time_ago_in_words(article.updated_at) %> ago</small>

        <div class="d-flex mt-2">
          <% if logged_in? && current_user == article.user%>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-sm btn-secondary mr-1" %>
            <%= button_to "Delete", article_path(article), method: :delete, class: "btn btn-sm btn-danger " %>
          <% end %>
        </div>

    </div>

    
  <% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>


<%= form_for @article, data: { turbo:false } do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div>
        

    <div class="form-group">
        <%= f.label :description %><br/>
        <%= f.text_field :description, class: "form-control" %>
    </div>

    <p>
        <%= f.submit 'Create', class: 'btn btn-primary' %>
    </p>
<% end %>

<%= link_to "Back to Articles", articles_path %>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit Article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<p><%= link_to "Create an Article", new_article_path, class: "btn btn-success" %></p>


<%= render "article", obj: @articles%>

<div class="text-center">
  <%= will_paginate(@articles,:previous_label => "Prev", :next_label => "Next") %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center">Create Article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h3>
    Title : <%= @article.title %>
</h3>

<p>
    Description : <%= @article.description %>
</p>

<p>
    <small>Author : <%= (link_to @article.user.username, user_path(@article.user)) if @article.user %> </small>
</p>

<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <a href="<%= edit_article_path(@article) %>">Edit Article </a> |
<% end %>

<%= link_to "Back to Articles", articles_path %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>


<%= form_for @category, data: { turbo:false } do |f| %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
    </div>
        
    <p>
        <%= f.submit 'Create', class: 'btn btn-primary' %>
    </p>
<% end %>

<%= link_to "Back to Categories", categories_path %>

app/views/categories/edit.html.erb
<h1 class="text-center">Edit Category</h1>

<%= render "form" %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>

    <div class="card-body bg-light mb-2">
        <h3><%= link_to category.name, category_path(category) %></h3>

        <div class="d-flex mt-2">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Edit", edit_category_path(category), class: "btn btn-sm btn-secondary mr-1" %>
            <%= button_to "Delete", category_path(category), method: :delete, class: "btn btn-sm btn-danger " %>
          <% end %>
        </div>

    </div>

    
  <% end %>

app/views/categories/new.html.erb
<h1 class="text-center">Add Category</h1>

<%= render "form" %>

app/views/layouts/_messages.html.erb
<% if flash[:success] %>
    <div class="alert alert-success">
        <%= flash[:success] %>
    </div>
<% end %>

<% if flash[:notice] %>
    <div class="alert alert-warning">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:danger] %>
    <div class="alert alert-danger">
        <%= flash[:danger] %>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Rails</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= articles_path %>">Articles</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu">
            <%= link_to "All Categories", categories_path, class: "dropdown-item" %>

            <% Category.all.each do |category|%>
              <%= link_to category.name, category_path(category), class: "dropdown-item" %>
            <% end %>


            <% if logged_in? and current_user.admin? %>
              <div class="dropdown-divider"></div>
              <%= link_to "New Category", new_category_path, class: "dropdown-item" %>
            <% end %>

          </div>
        </li>
      </ul>

     
      

      <% if logged_in? %>

        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="nav-item dropdown mr-auto">
            <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu">
              <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= button_to "Logout", logout_path, method: :delete, class: " dropdown-item" %>
            </div>
          </li>
        </ul>

      <% else %>
        <a class="nav-link" href="<%= signup_path %>">Signup</a>
        <a class="nav-link" href="<%= login_path %>">Login</a>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>


    <div class="container mt-2">
      <%= render "layouts/messages" %>

      <%= yield %>
    </div>

    <%= debug(params) if Rails.env.development? %>


    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger">
        <% obj.errors.full_messages.each do |message| %>
            <p>
                <%= message %>
            </p>
        <% end %>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, data: { turbo:false } do |f| %>
    <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %>
    </div>
        

    <div class="form-group">
        <%= f.label :email %><br/>
        <%= f.email_field :email, class: "form-control" %>
    </div>

     <div class="form-group">
        <%= f.label :password %><br/>
        <%= f.password_field :password, class: "form-control" %>
    </div>

    <p>
        <%= f.submit(@user.new_record? ? 'Sign Up': 'Update User', class: 'btn btn-primary') %>
    </p>
<% end %>

<%= link_to "Back to Articles", articles_path %>

app/views/users/_user.html.erb
<% obj.each do |user| %>

    <div class="offset-sm-3 col-sm-6 card-body bg-light mb-2 justify-content-center text-center">
        <p><%= gravatar_for user %></p>
        <h3><%= link_to user.username, user_path(user) %></h3>
        <p><%= pluralize(user.articles.count, "article") %></p>
        <%= button_to "Delete", user_path(user), method: :delete, class: "btn btn-sm btn-danger " %>

    </div>

    
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center">Edit User</h1>


<%= render 'shared/errors', obj: @user %>

<%= render "form"%>

app/views/users/index.html.erb
<h1 class="text-center">Users</h1>
<%= render "user", obj: @users%>

app/views/users/new.html.erb
<h1 class="text-center">Signup Form</h1>


<%= render 'shared/errors', obj: @user %>


<%= form_for @user, data: { turbo:false } do |f| %>
    <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %>
    </div>
        

    <div class="form-group">
        <%= f.label :email %><br/>
        <%= f.email_field :email, class: "form-control" %>
    </div>

     <div class="form-group">
        <%= f.label :password %><br/>
        <%= f.password_field :password, class: "form-control" %>
    </div>

    <p>
        <%= f.submit 'Sign Up', class: 'btn btn-primary' %>
    </p>
<% end %>

<%= link_to "Back to Articles", articles_path %>s

app/views/users/show.html.erb
<h1 class="text-center">Welcome to <%= @user.username %>'s page</h1>

<div class="text-center my-2">
    <%= gravatar_for @user %>
</div> 

<%= render "articles/article", obj: @user_articles %>

<div class="text-center">
  <%= will_paginate(@user_articles,:previous_label => "Prev", :next_label => "Next") %>
</div>